local library = loadstring(game:HttpGet("https://pastebin.com/raw/eKwyeQa0", true))()
local tab1 = library:CreateTab("Gun", true)
local button = library:MakeButton(tab1,"AK47",function(button)
   game.ReplicatedStorage.Events.Drop:FireServer(game.ReplicatedStorage.Weapons["AK47"], game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame, 30, 90, false, game.Players.LocalPlayer, false, false)
end)
local button1 = library:MakeButton(tab1,"M4A4",function(button)
   game.ReplicatedStorage.Events.Drop:FireServer(game.ReplicatedStorage.Weapons["M4A4"], game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame, 30, 90, false, game.Players.LocalPlayer, false, false)
end)
local button2 = library:MakeButton(tab1,"FAMAS",function(button)
   game.ReplicatedStorage.Events.Drop:FireServer(game.ReplicatedStorage.Weapons["Famas"], game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame, 25, 100, false, game.Players.LocalPlayer, false, false)
end)
local button3 = library:MakeButton(tab1,"SG553",function(button)
   game.ReplicatedStorage.Events.Drop:FireServer(game.ReplicatedStorage.Weapons["SG"], game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame, 30, 90, false, game.Players.LocalPlayer, false, false)
end)
local button4 = library:MakeButton(tab1,"G3SG1",function(button)
   game.ReplicatedStorage.Events.Drop:FireServer(game.ReplicatedStorage.Weapons["G3SG1"], game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame, 20, 80, false, game.Players.LocalPlayer, false, false)
end)
local button5 = library:MakeButton(tab1,"AWP",function(button)
   game.ReplicatedStorage.Events.Drop:FireServer(game.ReplicatedStorage.Weapons["AWP"], game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame, 10, 30, false, game.Players.LocalPlayer, false, false)
end)
local button6 = library:MakeButton(tab1,"Scout",function(button)
   game.ReplicatedStorage.Events.Drop:FireServer(game.ReplicatedStorage.Weapons["Scout"], game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame, 10, 90, false, game.Players.LocalPlayer, false, false)
end)
local button7 = library:MakeButton(tab1,"Tec9",function(button)
   game.ReplicatedStorage.Events.Drop:FireServer(game.ReplicatedStorage.Weapons["Tec9"], game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame, 18, 126, false, game.Players.LocalPlayer, false, false)
end)
local button8 = library:MakeButton(tab1,"FiveSeven",function(button)
   game.ReplicatedStorage.Events.Drop:FireServer(game.ReplicatedStorage.Weapons["FiveSeven"], game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame, 20, 100, false, game.Players.LocalPlayer, false, false)
end)
local button9 = library:MakeButton(tab1,"USP",function(button)
   game.ReplicatedStorage.Events.Drop:FireServer(game.ReplicatedStorage.Weapons["USP"], game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame, 13, 26, false, game.Players.LocalPlayer, false, false)
end)
local tab2 = library:CreateTab("fuck", true)
local button10 = library:MakeButton(tab2,"MAG-7",function(button)
   game.ReplicatedStorage.Events.Drop:FireServer(game.ReplicatedStorage.Weapons["MAG7"], game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame, 5, 35, false, game.Players.LocalPlayer, false, false)
end)
local button11 = library:MakeButton(tab2,"MG42",function(button)
   game.ReplicatedStorage.Events.Drop:FireServer(game.ReplicatedStorage.Weapons["MG42"], game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame, 150, 300, false, game.Players.LocalPlayer, false, false)
end)
local button12 = library:MakeButton(tab2,"M249",function(button)
   game.ReplicatedStorage.Events.Drop:FireServer(game.ReplicatedStorage.Weapons["M249"], game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame, 100, 200, false, game.Players.LocalPlayer, false, false)
end)
local button13 = library:MakeButton(tab2,"Deagle",function(button)
   game.ReplicatedStorage.Events.Drop:FireServer(game.ReplicatedStorage.Weapons["DesertEagle"], game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame, 7, 35, false, game.Players.LocalPlayer, false, false)
end)
local button14 = library:MakeButton(tab2,"R8",function(button)
   game.ReplicatedStorage.Events.Drop:FireServer(game.ReplicatedStorage.Weapons["R8"], game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame, 6, 18, false, game.Players.LocalPlayer, false, false)
end)
